### ISSUE TITLE
Add call to Aerosol Surface Area Update

### ISSUE THREAD

**Issue by bnmurphy** [bhutzell/CMAQ.Create_EBI_Solver#1]
Would be great to add the aerosol surface area subroutine call directly to the EBI solver template. I can help with this, and it's just a one-liner, but I need a bit more info on how things are structured in this code.

**Comment by bhutzell** [comment]
Ben,

I’ve add the change into an off-line repository of the creation routine. The github and soli repositories will be updated after your relevant pull request is accomplished. Yea, I know that you assigned me to review this pull request. I just don’t work as fast as the code sprinters.

-Bill
